br.com.alura.service.BitcoinService/mp-rest/url=https://www.strava.com/api/v3

# URL do banco de dados
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/app
quarkus.datasource.username=usuario
quarkus.datasource.password=senha

# Configurações do Pool de Conexões
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.reactive.url=jdbc:mysql://localhost:3306/app?useSSL=false
quarkus.datasource.reactive.driver=com.mysql.cj.jdbc.Driver
quarkus.hibernate-orm.database.generation=update